#!/usr/bin/with-contenv sh

set -e # Exit immediately if a command exits with a non-zero status.

# Make sure we appear with a proper name under `ps`.
if [ ! -L "$0" ]; then
    SV_NAME="$(basename "$(pwd)")"
    ln -sf run "$SV_NAME"
    exec ./"$SV_NAME" "$@"
fi

log() {
    echo "[$(basename "$0")] $*"
}

if [ -z ${USERID_NGINX+x} ]; then USERID_NGINX=0; fi
if [ -z ${GROUPID_NGINX+x} ]; then GROUPID_NGINX=0; fi

log "starting..."
while true; do
    s6-applyuidgid -u $USERID_NGINX -g $GROUPID_NGINX -G ${SUP_GROUP_IDS:-$GROUP_ID} /usr/sbin/logrotate -s /config/logrotate.status /etc/logrotate.conf
    EXITVALUE=$?
    if [ $EXITVALUE != 0 ]; then
        log "exited abnormally with [$EXITVALUE]"
    fi
    sleep 3600
done

# vim:ft=sh:ts=4:sw=4:et:sts=4
